name: Build and Deploy
on: [push]
permissions: write-all
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: vuepress-deploy
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: kasmh-odoo/odoo-technical-course
          TARGET_BRANCH: main
          NODE_OPTIONS: --openssl-legacy-provider
          BUILD_SCRIPT: git config --global --add safe.directory "*" && npm install && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
